Repository sayho-karly/sayho-karly, pull requests merged in 2023-08, with the labels that each got.

#60 [modify, refactor] 함수 리팩토링 , html 스크립트 추가
  client/cart-modal.html
  client/cart.html
  client/css/main.css
  client/detail.html
  client/index.html
  client/js/login.js
  client/js/logout.js
  client/js/render.js
  client/js/signup.js
  client/lib/utils/elementVisible.js
  client/lib/utils/generateRandomID.js
  client/lib/utils/index.js
  client/lib/utils/validation.js
  client/login.html
  client/signup.html
Labels: feat, refactor, dev

#62 [Merge] [Modify]Main 장바구니 담기 클릭시 해당 상품 ID값, 수량 스토리지에 저장하기
  client/cart-modal.html
  client/cart.html
  client/css/main.css
  client/index.html
  client/js/cart.js
  client/js/main.js
  client/js/test.js
  server/db/data.json
Labels: modify, merge

#69 [Modify] [feat] 대체텍스트 부여 장바구니 알림창 구현
  client/cart-modal.html
  client/cart.html
  client/css/main.css
  client/detail.html
  client/index.html
  client/js/cart.js
  client/js/main.js
  client/js/test.js
  client/login.html
  client/main.html
  client/signup.html
Labels: modify, feat, style
